
<footer>
    <div class="wrapper">
        <p>&copy; 2025 Nhom Nhom. All rights reserved.</p>
        <div id="footer-links">
            <ul>
                <li><h5>Company</h5></li>
                <li><a href="about.php">Team</a></li>
                <li><a href="https://nhomnhom.atlassian.net/jira/software/projects/SCRUM/summary">Jira</a></li>
                <li><a href="jobs.php">Careers</a></li>
                <li><a href="https://github.com/105730519/Project-part-2.git">Github</a></li>
            </ul>
            <ul>
                <li><h5>Connect</h5></li>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">X</a></li>
                <li><a href="#">LinkedIn</a></li>
                <li><a href="#">Instagram</a></li>
            </ul>
            <ul>
                <li><h5>Help</h5></li>
                <li><a href="#" title="Need support?">Support</a></li>
                <li><a href="#" title="Contact our team">Contact</a></li>
            </ul>
        </div>
    </div>
</footer>
