<!DOCTYPE html>
<html lang="en">
<!--Tran Minh Thien Phan - 105730519-->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Nhom Nhom Careers</title>
    <link rel="stylesheet" href="styles/styles.css">
    <link href="http://fonts.googleapis.com/css?family=Crete+Round" rel="stylesheet" type="text/css">
</head>
<body class="index">