<header class="company-name">
    <h1>Nhom Nhom<span class="color">.</span></h1>
    <nav>
        <ul>
            <li><a href="index.php" title="Go to homepage">Home</a></li>
            <li><a href="jobs.php" title="View job oppenings">Jobs</a></li>
            <li><a href="apply.php" title="Apply for a job">Apply</a></li>
            <li><a href="about.php" title="Meet our team">About</a></li>
        </ul>
    </nav>
</header>
